name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'

jobs:
  renovate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.RENOVATE_APP_ID }}
          installation_id: ${{ secrets.RENOVATE_INSTALL_ID }}
          private_key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v39.2.4
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_ONBOARDING: "false"
          RENOVATE_PLATFORM_COMMIT: "true"
        with:
          configurationFile: .github/renovate.json
          token: ${{ steps.generate_token.outputs.token }}
